# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: AutoCert

on:
  schedule:
    - cron:  '30 5 */2 * *'
  workflow_dispatch:

env:

  EMAIL: ${{ secrets.EMAIL }}
  CDNAccessKeyId: ${{secrets.CDNACCESSKEYID}}
  CDNAccessKeySecret: ${{secrets.CDNACCESSKEYSECRET}}
  DNSAccessKeyId: ${{secrets.DNSACCESSKEYID}}
  DNSAccessKeySecret: ${{secrets.DNSACCESSKEYSECRET}}
  

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.1

    - name: Set up Go
      uses: actions/setup-go@v5.2.0
      with:
        go-version: '1.23'
        check-latest: true
        cache-dependency-path: "**/*.mod"
          
    - name: Mod
      run: go mod tidy  && go mod download
    - name: Build
      run: go build -o AutoCert cmd/main.go
    - name: ${{vars.DOMAINTOOLS}}
      run: ./AutoCert --domain=${{vars.DOMAINTOOLS}} --email=${{env.EMAIL}} --product=cdn --renew --dns-access-key-id=${{env.DNSAccessKeyId}} --dns-access-key-secret=${{env.DNSAccessKeySecret}} --cdn-access-key-id=${{env.CDNAccessKeyId}} --cdn-access-key-secret=${{env.CDNAccessKeySecret}}
    - name: ${{vars.DOMAINCLASSROOMS}}
      run: ./AutoCert --domain=${{vars.DOMAINCLASSROOMS}} --email=${{env.EMAIL}} --product=cdn --renew --dns-access-key-id=${{env.DNSAccessKeyId}} --dns-access-key-secret=${{env.DNSAccessKeySecret}} --cdn-access-key-id=${{env.CDNAccessKeyId}} --cdn-access-key-secret=${{env.CDNAccessKeySecret}}
    - name: ${{vars.DOMAINICUA}}
      run: ./AutoCert --domain=${{vars.DOMAINICUA}} --email=${{env.EMAIL}} --product=cdn --renew --dns-access-key-id=${{env.DNSAccessKeyId}} --dns-access-key-secret=${{env.DNSAccessKeySecret}} --cdn-access-key-id=${{env.CDNAccessKeyId}} --cdn-access-key-secret=${{env.CDNAccessKeySecret}}

